clc;
clear all;
close all;

tractList = {'Anterior Commissure'; 'Anterior Corona Radiata Left';'Anterior Corona Radiata Right'; 'Anterior Limb Internal Capsule Left';'Anterior Limb Internal Capsule Right';'Body Corpus Callosum';...
            'Cingulum Cingulate Gyrus Left';'Cingulum Cingulate Gyrus Right'; 'Cingulum Hippocampal Left'; ...
            'Cingulum Hippocampal Right';'Cerebral Peduncle Left';'Cerebral Peduncle Right';...
            'Corticospinal Tract Left';'Corticospinal Tract Right';'Frontal Lobe Left';'Frontal Lobe Right';'Fornix Left';'Fornix Right';'Fornix Stria Terminalis Left';'Fornix Stria Terminalis Right';...
            'Genu Corpus Callosum';'Inferior Cerebellar Peduncle Left';'Inferior Cerebellar Peduncle Right'; ...
            'Inferior Fronto Occipital Fasciculus Left';'Inferior Fronto Occipital Fasciculus Right';'Inferior Longitudinal Fasciculus Left';'Inferior Longitudinal Fasciculus Right';...
            'Midbrain';'Middle Cerebellar Peduncle';'Medial Lemniscus Left';'Medial Lemniscus Right';'Occipital Lobe Left';'Occipital Lobe Right'; ...
            'Olfactory Radiation Left';'Olfactory Radiation Right';'Optic Tract';...
            'Posterior Corona Radiata Left';'Posterior Corona Radiata Right';'Pontine Crossing Tract';...
            'Posteriorlimb Internal Capsule Left';'Posteriorlimb Internal Capsule Right';'Parietal Lobe Left';'Parietal Lobe Right';...
            'Posterior Thalamic Radiation Left';'Posterior Thalamic Radiation Right';'Splenium Corpus Callosum';...
            'Superior Cerebellar Peduncle Left';'Superior Cerebellar Peduncle Right';'Superior Corona Radiata Left';'Superior Corona Radiata Right'; ...
            'Superior Fronto Occipital Fasciculus Left';'Superior Fronto Occipital Fasciculus Right';'Superior Longitudinal Fasciculus Left';'Superior Longitudinal Fasciculus Right';...
             'Sagittal Stratum Left';'Sagittal Stratum Right';'Tapetum Corpus Callosum';'Temporal Lobe Left';'Temporal Lobe Right';'Uncinate Fasciculus Left';'Uncinate Fasciculus Right'};
        
mat_file = dir(fullfile(['/home-local/bayrakrg/Dropbox (VUMC)/tractEM/BLSA/BLSA_mat/' '*dice.mat']));

for t = 1:length(mat_file)
    dice_mat = load(fullfile(mat_file(t).folder, mat_file(t).name));
    a = struct2cell(dice_mat);
    b = a{1,1}; % fields of 1x1 struct i.e. b = a{2,1}
    figure(1); boxplot(b)
    nameMe = strrep(dice_mat.nameMe,"_"," ");
    title(['Reproducibility for' tractList(t), '\fontsize{8}'])
    ylabel('dice coefficient')
%     xticklabels('avg')
    xticklabels(dice_mat.nameMe);
    xtickangle(45);

%     %set(figure(1),'Position', [1 1 1680 1050]);
%     name = mat_file(t).name(1:end-9);
%     saveas(figure(1),['/home-local/bayrakrg/Dropbox (VUMC)/BLSA/BLSA_Dice_plots/dice_per_subject/' 'dice_' name '.jpg']); 
%     close all;
end